import logging
import time
from typing import Dict, Any

# pyrefly: ignore [missing-import]
from src.nlu.intent import Intent, IntentType
# pyrefly: ignore [missing-import]
from src.tasks.registry import TaskRegistry
# pyrefly: ignore [missing-import]
from src.tasks.exceptions import TaskError, HandlerNotFoundError, TaskExecutionError
# pyrefly: ignore [missing-import]
from src.utils.metrics import metrics

logger = logging.getLogger(__name__)

class TaskExecutor:
    """
    The main entry point for executing business logic. 
    It receives an Intent, looks up the correct handler in the TaskRegistry, 
    executes it safely, and returns a standardized context dictionary for the LLM.
    """
    
    def execute(self, intent: Intent) -> Dict[str, Any]:
        """
        Executes the task associated with the given intent.
        
        :param intent: The Intent object generated by the NLU engine.
        :return: A dictionary containing the execution state and results, 
                 which will be injected into the LLM prompt.
        """
        start_time = time.time()
        
        # 1. Handle UNKNOWN intents immediately without checking the registry
        if intent.type == IntentType.UNKNOWN or not intent.is_reliable:
            logger.info("Skipping task execution for UNKNOWN or low-confidence intent.")
            return {
                "status": "skipped",
                "reason": "unrecognized_intent",
                "message": "I didn't understand the request well enough to take action."
            }

        # 2. Fetch the handler
        try:
            handler = TaskRegistry.get_handler(intent.type)
        except HandlerNotFoundError as e:
            # We know what they want, but we haven't built the feature yet.
            logger.error(str(e))
            return {
                "status": "error",
                "error_type": "HandlerNotFoundError",
                "message": "I understand what you want, but I don't have the capability to do that yet."
            }

        # 3. Execute the handler safely
        logger.info(f"Executing task for intent: {intent.type.value}")
        try:
            # Track how many times this specific intent was executed
            metrics.increment(f"task_executed_{intent.type.value}")
            
            # Run the business logic
            result_data = handler.execute(intent)
            
            # Calculate how long execution took
            duration_ms = (time.time() - start_time) * 1000
            metrics.record_latency("task_execution_total", duration_ms)
            logger.debug(f"Task {intent.type.value} completed in {duration_ms:.1f}ms")
            
            return {
                "status": "success",
                "intent_executed": intent.type.value,
                "data": result_data  # E.g., {"temperature": 72, "conditions": "sunny"}
            }
            
        except Exception as e:
            # Catch ANY error the handler throws so it doesn't crash the main pipeline
            error_msg = f"Failed while executing {intent.type.value}: {str(e)}"
            logger.error(error_msg, exc_info=True)
            return {
                "status": "error",
                "error_type": "TaskExecutionError",
                "intent_attempted": intent.type.value,
                "message": "I encountered an internal error while trying to complete your request."
            }
