import numpy as np
import logging

logger = logging.getLogger(__name__)

class TTSAudioProcessor:
    """
    Post-processes the raw audio waveform generated by the TTS Synthesizer (e.g., Piper)
    before it is sent to the physical speakers.
    
    This ensures the voice is loud, clear, and doesn't have awkward silent pauses
    at the beginning or end of the sentence.
    """
    
    @staticmethod
    def normalize_audio(audio_data: np.ndarray, target_peak: float = 0.95) -> np.ndarray:
        """
        Normalizes the audio array so the loudest peak hits the target_peak amplitude.
        This prevents the TTS from being too quiet to hear, or so loud that it distorts
        and blows out the speakers.
        
        :param audio_data: 1D numpy array of audio samples.
        :param target_peak: The maximum amplitude (0.0 to 1.0).
        :return: Normalized numpy array.
        """
        if len(audio_data) == 0:
            return audio_data
            
        # Find the maximum absolute amplitude in the current audio
        current_peak = np.max(np.abs(audio_data))
        
        if current_peak == 0:
            return audio_data  # It's completely silent, don't divide by zero
            
        # Calculate the multiplier needed to reach the target peak
        gain = target_peak / current_peak
        
        # Apply the gain
        normalized = audio_data * gain
        
        return normalized

    @staticmethod
    def trim_silence(audio_data: np.ndarray, threshold: float = 0.01) -> np.ndarray:
        """
        Removes dead silence from the very beginning and very end of the generated audio.
        Some TTS engines (like Piper) occasionally generate 0.5s of silence before they 
        start speaking, which makes the assistant feel laggy.
        
        :param audio_data: 1D numpy array of audio samples.
        :param threshold: The amplitude threshold below which is considered "silence".
        :return: Trimmed numpy array.
        """
        if len(audio_data) == 0:
            return audio_data
            
        # Find all indices where the audio amplitude is above the threshold
        active_indices = np.where(np.abs(audio_data) > threshold)[0]
        
        if len(active_indices) == 0:
            return audio_data # The whole clip is silence
            
        # Get the first and last index of actual sound
        start_idx = active_indices[0]
        end_idx = active_indices[-1]
        
        # Slice the array to keep only the active part
        trimmed = audio_data[start_idx:end_idx + 1]
        
        logger.debug(f"Trimmed {start_idx} frames from start and {len(audio_data) - end_idx} from end.")
        return trimmed

    @classmethod
    def process_for_playback(cls, audio_data: np.ndarray) -> np.ndarray:
        """
        The main pipeline method. Runs all necessary post-processing steps 
        in the correct order before playback.
        """
        # Ensure it's float32 for processing
        if audio_data.dtype != np.float32:
            audio_data = audio_data.astype(np.float32)
            
        audio = cls.trim_silence(audio_data)
        audio = cls.normalize_audio(audio)
        
        return audio
